services:
  app:
    build:
      context: .           # Le contexte de build est toujours le répertoire racine
      dockerfile: fournisseurIdentiteApi/Dockerfile
    container_name: springboot_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fournisseur
      SPRING_DATASOURCE_USERNAME: fournisseur
      SPRING_DATASOURCE_PASSWORD: fournisseur
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fournisseur
      POSTGRES_USER: fournisseur
      POSTGRES_PASSWORD: fournisseur
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
